#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Nov 12, 2019 08:37:37 AM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



    menu .pop50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) \
        -font $vTcl(actual_gui_font_menu_desc) -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop50" "Popupmenu1" vTcl:WidgetProc "" 1
    menu .pop51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) \
        -font $vTcl(actual_gui_font_menu_desc) -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop51" "Popupmenu2" vTcl:WidgetProc "" 1

proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background $vTcl(actual_gui_bg) \
        -highlightbackground #f0f0f0f0f0f0 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x580+525+163
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 800 600
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Dashboard"
    vTcl:DefineAlias "$top" "dashboard" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m48
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#tablero} \
        -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(pr,menufgcolor) -label Tablero 
    $site_3_0 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#campania} \
        -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(pr,menufgcolor) -label Campaña 
    $site_3_0 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#salir} \
        -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(pr,menufgcolor) -label Salir 
    ttk::combobox $top.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo47" "TCombobox1" vTcl:WidgetProc "dashboard" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tCo47 \
        -in $top -x 320 -y 200 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

