import os

DIRSEPARATION = os.sep
BASEPATH = os.getcwd()
APPLICATIONDIR = 'src' + DIRSEPARATION
ASSETSDIR = BASEPATH + DIRSEPARATION + ( APPLICATIONDIR if len(APPLICATIONDIR) > 0 else '') + 'assets' + DIRSEPARATION
IMAGESDIR = ASSETSDIR + DIRSEPARATION + 'images' + DIRSEPARATION